# This file provides configurations for tox-based project development and management automation
# tasks.

# Base tox configurations.
[tox]
requires =
    tox>=4,<5
    tox-uv>=1,<2
envlist = docs

# This forces tox to create a 'sterile' environment into which the project with all dependencies
# is installed prior to running the requested tasks, isolating the process from the rest of the
# system.
isolated_build = True

[testenv:docs]
skip_install = true
description =
    Builds the API documentation from source code docstrings using Doxygen, Breathe and Sphinx.
    The result can be viewed by loading 'docs/build/html/index.html'.
deps = ataraxis-automation==8.1.0
allowlist_externals = doxygen
commands =
    doxygen Doxyfile
    sphinx-build -b html -d docs/build/doctrees docs/source docs/build/html -j auto -v
